### PR TITLE
Build the pipeline.

### PR DESCRIPTION
**Pull request by nirgn975**
#1

### CODE REVIEW

**Comment by nirgn975** [comment]
Electron error:
elm_and_youtube-playlist_ _gulp_ _electron_helper_ _gulp_term_program_apple_terminal

But when loading it on chrome, it works fine:
elm_and_main-electron_js_ __users_nirgalon_webstormprojects_youtube-playlist_and_c4m_features_og_events_module_-_capacity4more_-___applications_mamp_htdocs_capacity4more__and_downloads

**Comment by nirgn975** [comment]
@amitaibu @bitamar Anyone know why?

**Comment by bitamar** [comment]
Probably main.js was not loaded at all.
I'm guessing it's an issue with electron-gulp configuration.

**Comment by bitamar** [comment]
Make sure main.js is copied to same directory where the index.html you open with electron is.

**Pull request merged**
